NUMPY 
ARRAYS IN NUMPY

NumPy (Numerical Python) is a popular Python library used for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [5]:
import numpy as np

In [6]:
arr = np.array([[2,3,4],[4,2,1]])
type(arr)

numpy.ndarray

In [7]:
arr.ndim # number of dimensions

2

In [8]:
arr.shape # number pf rows and columns

(2, 3)

In [9]:
arr.size # total number of elements

6

In [10]:
arr.dtype

dtype('int32')

In [11]:

# create array from list with type float
a = np.array([[1,23,3],[4,5,6]], dtype='float')
print("array created using passed list: \n", a)

array created using passed list: 
 [[ 1. 23.  3.]
 [ 4.  5.  6.]]


In [12]:
#create array from tuple
b = np.array([[2,4,3,5],[4,3,4,2]])
print("array is : \n", b)

array is : 
 [[2 4 3 5]
 [4 3 4 2]]


In [13]:
c = np.zeros((2,3),dtype= int)
print("the array of zeroes is:\n", c)

the array of zeroes is:
 [[0 0 0]
 [0 0 0]]


In [14]:
c = np.ones((2,3))


In [15]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(3) # identity matrix of size 3 by 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.arange(0, 30, 5)
print(a)
# Uses start, stop, and step, use when When step size is known
# Use arange when you know the step size and don’t need to include the endpoint.

[ 0  5 10 15 20 25]


In [ ]:
b = np.linspace(0,5,10)
print(b)
# Uses start, stop, and num use When number of points needed is known.
# Use linspace when you need a specific number of evenly spaced points between start and stop, including the endpoint by default.

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
arr = np.array([[1,2,5],
                [4,2,6]])
newarr = arr.reshape(3,2)

In [20]:
newarr

array([[1, 2],
       [5, 4],
       [2, 6]])

In [ ]:
# flattened - flatten into 1D array

In [21]:
# Indexing 
arr

array([[1, 2, 5],
       [4, 2, 6]])

In [ ]:
arr[1:, :2] # from row 1 till end and from column start to second row, can do step size also

array([[4, 2]])

In [29]:
# Broadcasting feature:
# add 1 to every element, if you write a+1 and it will be directed to every ele of an array
a = np.array([2,3,4,5])
a+1

array([3, 4, 5, 6])

In [28]:
a*2

array([ 4,  6,  8, 10])

In [ ]:
# Transpose of array: use a.T
a= np.array([[1,2,3], [4,5,6],[4,7,8]])
print("original array is : \n", a)
print("transpose of array is : \n", a.T)

original array is : 
 [[1 2 3]
 [4 5 6]
 [4 7 8]]
transpose of array is : 
 [[1 4 4]
 [2 5 7]
 [3 6 8]]


In [32]:
# rowwise maximum element, axis =1 means you want to read by rowwise
# axis = 0 means want to read by columnwise
arr = np.array([[2,3,4],
               [5,6,7],
               [8,9,0]])
print("largest element is : ", arr.max())
print("rowwise max ele is : ", arr.max(axis=1))
print("columnwise max ele is : ", arr.max(axis=0))

largest element is :  9
rowwise max ele is :  [4 7 9]
columnwise max ele is :  [8 9 7]


In [ ]:
# Sorting:
# specify sort algorithm - kind = 'mergesort' 
a = np.array([[2,3,4],[10,6,7],[7,8,9]])
print("array sorted order is : ", np.sort(a, axis=None))

print("rowwise : \n", np.sort(a, axis=1))

print("column-wise: \n", np.sort(a, axis=0, kind='mergesort'))

array sorted order is :  [ 2  3  4  6  7  7  8  9 10]
rowwise : 
 [[ 2  3  4]
 [ 6  7 10]
 [ 7  8  9]]


In [ ]:
# Stacking and Splitting:
# np.vstack - to stack arrays along vertical axis
# np.hstack - to stack arrays along horizontal axis
# np.column_stack - to stack 1-D arrays as columns into 2D arrays.
# np.concatenate - to stack arrays along specified axis(axis is passed as argument)

# np.split - to split an array into sub-arrays of equal size along specified axis(axis is passed)
# np.hsplit
# np.vsplit
# np.array_split- split array along specified axis

# More functions:
# min,max
# mean
# median
# average
# variance
# standard deviation
